kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: env-tz
  version: "1.0"
  namespace: BE_PR_BANK
  tags: []
spec:
  variables:
    - key: X-IBM-Client-Id_value
      isSecret: false
      value: 559c927663c838ec07eb0ac2645c7288
